Repository savushkin-r-d/PLCnext-howto, pull requests merged in 2020-01, with the labels that each got.

#11 Fix preprocessor defines
  HowTo install Linux (Ubuntu) tools for C++ programming with Eclipse IDE/readme.md
Labels: bug

#7 Update readme.md
  HowTo install Linux (Ubuntu) tools for C++ programming with Eclipse IDE/readme.md
Labels: doc, enhancement

#5 [update] version 2019.9
  HowTo install Linux (Ubuntu) tools for C++ programming with Eclipse IDE/readme.md
Labels: doc, enhancement, good first issue

#12 Fix path settings
  HowTo install Linux (Ubuntu) tools for C++ programming with Eclipse IDE/images/cdt_cross_linker_settings.png
  HowTo install Linux (Ubuntu) tools for C++ programming with Eclipse IDE/images/cdt_cross_settings.png
  HowTo install Linux (Ubuntu) tools for C++ programming with Eclipse IDE/images/cdt_includes.png
  HowTo install Linux (Ubuntu) tools for C++ programming with Eclipse IDE/readme.md
Labels: bug, doc

#10 [Update] readme.md
  HowTo install Linux (Ubuntu) tools for C++ programming with Eclipse IDE/readme.md
Labels: doc, enhancement
